### ISSUE TITLE
[8일] 도서관리자는 주문내역을 바탕으로 출고처리할 수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/wms-book#107]
# 👉 공지
- 드디어 마지막 이슈입니다. 그동안 쌓아온 트랜잭션처리와 조인쿼리를 모두 활용해봅시다.
- 6일차의 조인쿼리 처리를 최대한 활용해서 이번 출고처리기능을 구현해봅시다.
- **실제 코드구현도 중요하지만 그 이전에 기능의 처리흐름을 mvc패턴위에서 계획해보는 것이 중요합니다. 이는 여러번 반복연습이 필요합니다.**
- 슈퍼레시피를 하나 개발하기 위해서 요리사는 해당레시피대로 여러번 만들어보면서 수정-완성해갈겁니다. 여러분이 하는 작업도 다르지 않습니다. 여기까지 8일차의 여정을 돌아보고 수정-보완하는 시간이 또 필요할겁니다. 우리는 초보니까요. 조급해말고, 집중해주세요, 적절한 시간을 투자해주세요~ 시간이 없다는 핑계대신 시간을 만들어주시고요. 그 시간이 쌓이고, 뭉쳐져 여러분의 초석이 되줄겁니다. 👊 

# 🌈 Success criteria
1. 도서관리자는 재고메뉴중 주문내역을 바탕으로 출고처리 할수 있습니다.
2. 출고를 선택하면, `주문확인중`상태인 주문내역을 목록으로 조회할 수 있습니다.
3. 특정주문을 선택하면 주문아이템별로 출고된 내역만큼 차감처리되어야 합니다. 
4. 모든 출고가 정상적으로 처리된 경우, 해당 주문의 상태는 `발송완료`로 변경되어야 합니다. 

# 👷To-do
- [x] 주문내역 목록 조회 구현 (7일차 주문상태 조회 메소드 가져오기)
- [x] 주문ID(order_id)입력하면 tbl_order의 order_id 조회 -> tbl_order의 List<OrderDto> 조회 
-> tbl_order_item의 book_id -> tbl_inventory의 book_id조회하는 findOrderBook메소드 구현
- [x] if로 출고 정상 처리된 경우, 책 수량을 update하는 updateInventory메소드 구현
- [x] 입력한 주문ID의 status를 '발송완료'로 바꾸는 updateStatus 메소드 구현

# 👓 Review

### 출고 전
주문 테이블의 주문번호 11번의 status 주문확인중
![Image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/62885b2f-925d-4241-b7c6-3aacb6139df6)

주문번호 11번의 도서별 주문내역
![Image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/f3a691d1-b388-45e8-9117-32aff74129bf)

재고 테이블의 book_id 1번은 100권 2번은 50권 소유중 
![Image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/ca44c1a6-a3f7-49e6-89ca-3f027c8ce108)

### 출고 메소드 호출 후
재고 테이블에 출고한 만큼 수량이 감소됐다.
![Image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/2e93979b-79d4-454d-a238-5f719e36f3db)

status 발송완료로 변경
![Image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/a2b59fa8-49e4-4568-9a23-335fe524a28e)

tbl_order에 없는 order_id를 입력할 경우 오류 출력
![Image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/8ff0711b-652c-4ee8-b48c-5d091928b0b7)

**Comment by vlshzl35** [comment]
To-do 2번 구현중
OrderDto를 메인으로 resultMap을 만들면 1:N, 1:1관계가 만들어지는데 inventoryMapper니까 resultMap의 메인을 inventory로 하려니 1:N다음 N:1이 나온다.

![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/3e2e8335-84fa-4985-8cd1-9d6d87aab960)
이렇게 해야하나? 쿼리부터 잘 모르겠다

![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/9c9e1aa5-5981-41b9-a0c7-4b14cbc01a11)


###  #re
7일차에서 id로 주문을 조회하는 메소드를 활용하면  resultMap을 사용하지 않아도 되어 resultMap을 사용해 구현하지 않았다.

**Comment by vlshzl35** [comment]
리팩토링 할 것
- [ ] 주문ID를 입력할때 주문확인중이 아닌 주문ID를 선택할 수 있어 예외처리 필요
- [ ] 테스트코드 만들기 (테스트 만드는게 어렵다😥)
