### ISSUE TITLE
[8일] 도서관리자는 주문내역을 바탕으로 출고처리할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/wms-book#109]
# 👉 공지
- 드디어 마지막 이슈입니다. 그동안 쌓아온 트랜잭션처리와 조인쿼리를 모두 활용해봅시다.
- 6일차의 조인쿼리 처리를 최대한 활용해서 이번 출고처리기능을 구현해봅시다.
- **실제 코드구현도 중요하지만 그 이전에 기능의 처리흐름을 mvc패턴위에서 계획해보는 것이 중요합니다. 이는 여러번 반복연습이 필요합니다.**
- 슈퍼레시피를 하나 개발하기 위해서 요리사는 해당레시피대로 여러번 만들어보면서 수정-완성해갈겁니다. 여러분이 하는 작업도 다르지 않습니다. 여기까지 8일차의 여정을 돌아보고 수정-보완하는 시간이 또 필요할겁니다. 우리는 초보니까요. 조급해말고, 집중해주세요, 적절한 시간을 투자해주세요~ 시간이 없다는 핑계대신 시간을 만들어주시고요. 그 시간이 쌓이고, 뭉쳐져 여러분의 초석이 되줄겁니다. 👊 

# 🌈 Success criteria
1. 도서관리자는 재고메뉴중 주문내역을 바탕으로 출고처리 할수 있습니다.
2. 출고를 선택하면, `주문확인중`상태인 주문내역을 목록으로 조회할 수 있습니다.
3. 특정주문을 선택하면 주문아이템별로 출고된 내역만큼 차감처리되어야 합니다. 
4. 모든 출고가 정상적으로 처리된 경우, 해당 주문의 상태는 `발송완료`로 변경되어야 합니다. 

# 👷To-do
- [x]  `주문확인중`상태인 주문내역을 목록으로 조회 메서드 만들기 
- [x] 주문ID입력하면 order_id 조회 -> book_id -> inventory_id 조회해서 해당하는 InventoryDto 가져오는 메소드 구현 (주문아이템별로 출고된 내역만큼 차감처리 메서드 만들기 -> 수량 업데이트)
- [x] 모든 출고가 정상적으로 처리된 경우, 해당 주문의 상태는 `발송완료`로 변경하는 메서드 만들기 if로 출고 정상 처리된 경우, 책 수량을 update 메소드 구현 입력한 order_id의 status를 '발송완료'로 바꾸는 메소드 구현 (모든 출고가 정상적으로 처리된 경우, 해당 주문의 상태는 `발송완료`로 변경하는 메서드 만들기)

# 👓 Review
1. 출고를 선택하면 '주문확인중'상태인 주문내역을 목록으로 조회할 수 있씁니다.
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/6f695440-139e-4c6a-b943-262e6bcbed90)

2. 특정주문을 선택하면 주문아이템별로 출고된 내역만큼 차감처리되어야 합니다. 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/d675076f-0900-47d4-b1e7-34af37a843c4)

![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/cd4eba4a-2987-4eea-8ff3-73930dc26be3)

3.모든 출고가 정상적으로 처리된 경우, 해당 주문의 상태는 `발송완료`로 변경되어야 합니다. 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/dce4df6e-3dd9-4cac-88ac-c6d9f1b063dc)

**Comment by nnieun** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/01c82aa7-e360-4332-a27d-99dffec38130)
저 다른 분들꺼를 코드는 안건드렸는데 확인을 안하고 커밋을 해버렸습니다........... pr은 안날렸는데 어떻게 해결해야될까요 ...?

**Comment by nnieun** [comment]
https://github.com/nnieun/wms-book/commit/1f9f195aa20481059980223b385c358500ef052f
