### ISSUE TITLE
[8일] 도서 관리자는 주문내역을 바탕으로 출고처리할 수 있습니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/wms-book#114]
# 👉 공지
- 드디어 마지막 이슈입니다. 그동안 쌓아온 트랜잭션처리와 조인쿼리를 모두 활용해봅시다.
- 6일차의 조인쿼리 처리를 최대한 활용해서 이번 출고처리기능을 구현해봅시다.
- **실제 코드구현도 중요하지만 그 이전에 기능의 처리흐름을 mvc패턴위에서 계획해보는 것이 중요합니다. 이는 여러번 반복연습이 필요합니다.**
- 슈퍼레시피를 하나 개발하기 위해서 요리사는 해당레시피대로 여러번 만들어보면서 수정-완성해갈겁니다. 여러분이 하는 작업도 다르지 않습니다. 여기까지 8일차의 여정을 돌아보고 수정-보완하는 시간이 또 필요할겁니다. 우리는 초보니까요. 조급해말고, 집중해주세요, 적절한 시간을 투자해주세요~ 시간이 없다는 핑계대신 시간을 만들어주시고요. 그 시간이 쌓이고, 뭉쳐져 여러분의 초석이 되줄겁니다. 👊 

# 🌈 Success criteria
1. 도서관리자는 재고메뉴중 주문내역을 바탕으로 출고처리 할수 있습니다.
2. 출고를 선택하면, `주문확인중`상태인 주문내역을 목록으로 조회할 수 있습니다.
3. 특정주문을 선택하면 주문아이템별로 출고된 내역만큼 차감처리되어야 합니다. 
4. 모든 출고가 정상적으로 처리된 경우, 해당 주문의 상태는 `발송완료`로 변경되어야 합니다. 

# 👷To-do
- [ ] 도서관리자는 재고메뉴중 주문내역을 바탕으로 출고처리 할수 있습니다.
- [x] 출고를 선택하면, `주문확인중`상태인 주문내역을 목록으로 조회할 수 있습니다.
- [x] 특정주문을 선택하면 주문아이템별로 출고된 내역만큼 차감처리되어야 합니다. 
- [x] 모든 출고가 정상적으로 처리된 경우, 해당 주문의 상태는 `발송완료`로 변경되어야 합니다. 

# 👓 Review
1. <테스트 결과 스크린샷등 각종 이미지를 적극적으로 첨부합니다.>
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/70620dc5-6d7d-4dbe-8569-d83e6b3b20e6)
-> 재고 출고 입력 시 주문확인중 상태의 주문 목록 확인 및 출고할 주문 id 입력
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/9c57eef6-d8ea-429f-bda2-7c64f8461f2a)
-> 출고요청한 주문 id 주문상세조회
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/8e0941d7-18e9-42f8-86a2-e64120dc69f5)
-> 테이블도 바로 변경되어있음.
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/ba1a0460-9c98-4bc7-adde-fed16f1dfa0c)
-> inventory 테이블에 각자의 도서 id에 맞게 quantity 값이 100/50 에서 수량 4개씩 제외한 96/46으로 변경

**Comment by seongyeongit** [comment]
차감 처리를 xml 안에서만 구현하려다 보니 시간을 많이 씀..
-> service 단에서 해결하고 xml 안에서는 update 처리만!

**Comment by seongyeongit** [comment]
**테스트 없이 그냥 구현..
테스트 코드 먼저 짜는 연습 및 습관 들이기!!!**

**Comment by seongyeongit** [comment]
``` public List<OrderDto> getPendingOrdersWithInventory() {
        SqlSession sqlSession = getSqlSession();
        OrderMapper orderMapper = sqlSession.getMapper(OrderMapper.class);
        // 주문확인중 상태의 주문 목록 조회
        List<OrderDto> orders = orderMapper.selectOrdersByStatus(OrderableStatus.주문확인중);
        sqlSession.close();
        return orders;
    }

    public void processShipment(int orderId) throws Exception {
        SqlSession sqlSession = getSqlSession();
        OrderMapper orderMapper = sqlSession.getMapper(OrderMapper.class);
        InventoryMapper inventoryMapper = sqlSession.getMapper(InventoryMapper.class);
        try {
            // 주문 ID로 주문 조회
            OrderDto order = orderMapper.selectOrderById(orderId);
            System.out.println("Order Status: " + order.getStatus());
            // 주문 상태가 '주문확인중'인지 확인
            if (order != null && order.getStatus().equals(OrderableStatus.주문확인중)) {
                // 각 주문 아이템에 대해 재고 차감 처리
                for (OrderItemDto item : order.getOrderItems()) {
                    // 아이템의 책 ID에 해당하는 재고 목록 조회
                    List<InventoryDto> inventories = inventoryMapper.selectInventoryByBookId(item.getBookId());
                    int quantityToDecrement = item.getQuantity(); // 차감할 수량 설정
                    for (InventoryDto inventory : inventories) {
                        if (quantityToDecrement <= 0) break; // 더 이상 차감할 수량이 없으면 루프 종료
                        if (inventory.getQuantity() >= quantityToDecrement) {
                            // 현재 재고가 차감할 수량보다 크거나 같으면
                            inventory.setQuantity(inventory.getQuantity() - quantityToDecrement); // 재고에서 차감할 수량만큼 빼기
                            inventoryMapper.updateInventoryQuantity(inventory); // 재고 정보 업데이트
                            quantityToDecrement = 0; // 차감할 수량을 0으로 설정하여 루프 종료
                        } else {
                            // 현재 재고가 차감할 수량보다 적으면
                            quantityToDecrement -= inventory.getQuantity(); // 차감할 수량에서 현재 재고를 빼기
                            inventory.setQuantity(0); // 현재 재고를 0으로 설정
                            inventoryMapper.updateInventoryQuantity(inventory); // 재고 정보 업데이트
                        }
                    }
                    // 차감할 수량이 남아 있으면 재고 부족 예외 발생
                    if (quantityToDecrement > 0) {
                        throw new Exception("재고가 부족합니다.");
                    }
                }
                // 모든 아이템이 정상적으로 출고된 경우 주문 상태를 '발송완료'로 변경
                order.setStatus(OrderableStatus.발송완료);
                orderMapper.updateOrderStatus(order);
                sqlSession.commit(); // 트랜잭션 커밋
            } else {
                throw new Exception("유효하지 않은 주문 상태입니다."); // 주문 상태가 유효하지 않으면 예외 발생
            }
        } catch (Exception e) {
            sqlSession.rollback(); // 예외 발생 시 트랜잭션 롤백
            System.out.println("Exception: " + e.getMessage());
            throw e; // 예외 다시 던지기
        } finally {
            sqlSession.close(); // 세션 닫기
        }
    }
}

**Comment by seongyeongit** [comment]
[강사님의 리뷰]
- inventory 테이블의 quantity는 하나의 책에 대해서만 한 행씩 적용.
- List로 받아오면서 InventoryService가 복잡해진 듯 하니 바꿔보세요.
