### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by shqkel** [ssg-java3-240304/wms-book#19]
# 👉 공지
1. issue생성시, Assignees/Projects(wms-book)를 꼭 작성해주세요
2. pr생성시 각자의 issue를 꼭 링크해주세요.
3. db script가 업데이트 되었습니다. 꼭 새로 table을 생성해주세요.

# 🌈 Success criteria
1. 사용자는 첫화면에서 로그인/회원가입할 수 있습니다.
2. 로그인에 성공하면 사용자는 요구사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- [ ] 도메인별로 mvc패턴을 고려해 클래스를 모두 작성하세요.
- [ ] 제공된 테이블을 보고 entity클래스는 모두 작성하세요.
- [ ] <추가 할일 목록을 작성하고 실천합니다> 

# 👓 Review
1. <스크린샷 등을 적극활용해 구현 결과를 공유합니다.>
