### ISSUE TITLE
[1일] 프로젝트 개발 환경을 설정합니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/wms-book#2]
# 🌈 Success criteria
1. db를 구축합니다. book계정으로 wms_book_db에 테이블/샘플데이터를 추가합니다.
2. gradle 프로젝트를 생성하고, mybatis 실행환경을 설정합니다.
3. 적절히 SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👷To-do
- [x] root계정으로 book계정을 만듭니다. (패스워드 book)
- [x] root계정에서 wms_book_db를 생성합니다.
- [x] book계정이 wms_book_db의 사용권한을 부여합니다.
- [x] root계정에서 wms_book_db에 wms_book_db.sql을 실행합니다.
- [x] book계정에서도 wms_book_db 스키마를 생성하고 .sql을 실행합니다.
- [x] YangHeeyun폴더를 gradle로 import합니다.
- [x] MVC패턴을 적용해 폴더와 클래스를 생성합니다.
- [x] MyBatis 실행환경을 위해 설정합니다.
- [x] mybatis-config.xml, build.gradle, MyBatisTemplate을 작성합니다.
- [x] SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👓 Review
<테스트 결과 스크린샷등 각종 이미지를 적극적으로 첨부합니다.>
db구축
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/d65b5f5e-4004-49f6-ad66-9099fb25fa9a)

SqlSession을 가져오는 테스트 코드 작성
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/a8c94ead-9a6a-4bcd-9299-d86f34e4a3d5)

**Comment by vlshzl35** [comment]
양희윤
