### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/wms-book#20]
# 👉 공지
1. issue생성시, Assignees/Projects(wms-book)를 꼭 작성해주세요
2. pr생성시 각자의 issue를 꼭 링크해주세요.
3. db script가 업데이트 되었습니다. 꼭 새로 table을 생성해주세요.

# 🌈 Success criteria
1. 사용자는 첫화면에서 로그인/회원가입할 수 있다.
2. 로그인에 성공하면 사용자는 요구사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- [x] 도메인별로 mvc패턴을 고려해 클래스를 모두 작성하세요.
- [x] 제공된 테이블을 보고 entity클래스는 모두 작성하세요.
- [x] sql(Ver.2)로 db 변경
- [x] 로그인 실행과정 보여주는 view단(UserView) 생성

# 👓 Review
1. <스크린샷 등을 적극활용해 구현 결과를 공유합니다.>

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/e5aba38a-4dec-4b36-86ab-3a33377d549a)

**Comment by seongyeongit** [comment]
Q) switch문 안에서 while문 나가려면 if문 equlas조건으로 나가야하는거 만들어야하나요?

**Comment by seongyeongit** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/ba292f76-9381-4a5c-9dd5-d925ebcd5b75)
Q) Enum을 dto로 만들 때 model 하위에 enums 패키지 생성 후 OrderableStatus.java 생성하여 private OrderStatus status; 로 만들어야 하나요? 
-> 우선 사진말고 질문에 말한 것처럼 만들어서 pr 날려놨습니다!
