### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by Hong-ji-min** [ssg-java3-240304/wms-book#21]
# 🌈 Success criteria
1. 사용자는 첫화면에서 로그인/회원가입할 수 있다.
4. 로그인에 성공하면 사용자는 요구 사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- [x] 도메인별로 mvc패턴을 고려해 클래스를 모두 작성하세요.
- [x] 제공된 테이블을 보고 entity클래스는 모두 작성하세요.
- [x] 도메인 별, View 클래스를 작성합니다.

# 👓 Review
### Book
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/757b0572-685a-4a2e-ad61-15cbfc8e12a1)

### Inventory
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/1c60c2f0-1439-4755-81da-8a2641fad635)

### Order
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/561b8f7e-a423-4e55-bd46-caef2cc0bbf5)

### User
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/90173aa4-6b23-4ac3-8075-710dfda50b8a)

### Book
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/7f31da17-55af-4d58-8318-9f57a20f03cb)

### Inventory
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/235feaa7-0990-445d-a891-95395dacd245)

### Order
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/2a736af9-b698-4c81-9dff-3ea5c37e958f)
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/70d00e50-4d29-4440-bd03-f9314218f473)

### OrderItem
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/b3889c78-76b3-42a6-a198-928d3c2371de)

### User
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/33016428-2418-439e-aefa-2b1d43acc5da)
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/d3813dfe-164c-4351-a78e-7bc6d27824bd)

### MainView
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/ed11b9e4-9d45-472b-9588-93f87834f65b)

### UserView
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/5db24e40-065b-4154-8fa5-feeb40c71840)

### BookView
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/ffeb88bc-8fe2-4ec3-9887-e8f6fdfdd676)

### InventoryView
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/da1178ce-0136-4906-9f57-b1325caf70a2)

### OrderView
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/2987ae69-a309-4a48-8258-0378aa539f52)

**Comment by Hong-ji-min** [comment]
# 🖍Review
###  ✅변수 선언 위치를 고민해보기!
#### 1. 메소드 안
#### 2. 메소드안 특정 블럭
#### 3. 지역변수
> #### 변수 선언 위치 변경 전 
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/309ac694-519c-425f-94ed-73071549e671)

> #### 변수 선언 위치 변경 후
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/20b1a117-3edd-4ff4-8402-eab4cbe3007e)
<hr>

### 🎈알아두기❗
- #### insert 메소드의 return 타입 : `int`로 정해져 있음!
  -  Jdbc api가 preparestatement에서 정해놓은 게 있음
  - DML은 `행의 수`, DQL은 `resultset`으로 반환!
  
- #### 깃허브 commit message 
  - Update : 기존의 파일 내용을 수정할 때 
  - Feat : 새로운 파일 추가 or 기존의 파일에 새 기능 추가
