### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/wms-book#22]
# 👉 공지
1. issue생성시, Assignees/Projects(wms-book)를 꼭 작성해주세요
2. pr생성시 각자의 issue를 꼭 링크해주세요.
3. db script가 업데이트 되었습니다. 꼭 새로 table을 생성해주세요.

# 🌈 Success criteria
1. 사용자는 첫 화면에서 로그인/회원가입할 수 있다.
4. 로그인에 성공하면 사용자는 요구사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- [x] DB 새로 받기
- [x] 도메인별(Book, Inventory. Order)로 mvc패턴을 고려해 클래스를 모두 작성하세요.
- [x] 제공된 테이블을 보고 entity클래스(DTO)는 모두 작성하세요.

# 👓 Review
DTO 작성, 도메인별 mvc패턴 클래스 생성
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/c5c0806e-7562-45aa-9f75-c14c8e332901)

메인 -> 도서 관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/b551617a-e4f1-4492-a922-d3bbfddcca70)

메인 -> 재고 관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/12c969ad-0645-4046-97d9-a33e522ba1a4)

메인 -> 주문 관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/3eb62dcd-2071-453d-9faf-13af01659259)

**Comment by vlshzl35** [comment]
switch문 안에서 while문 나가려면 if문 equlas조건으로 나가야하는거 만들어야하는지 
예시)
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/eb73795d-e871-4f83-b6e7-42758124ade1)
A : 라벨을 만들어서 return 라벨명으로 알맞은 루프문 빠져나가게 구현하기

**Comment by vlshzl35** [comment]
Q2. 
제공된 테이블을 보고 entity클래스는 모두 작성하세요.가 DTO를 작성하라는 말인가요? 일단 view만했습니다

**Comment by vlshzl35** [comment]
Q2. enum파일 안에 한글은 value에만 넣을 수 있는게 맞나요?
