### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/wms-book#23]
# 👉 공지
1. issue생성시, Assignees/Projects(wms-book)를 꼭 작성해주세요
2. pr생성시 각자의 issue를 꼭 링크해주세요.
3. db script가 업데이트 되었습니다. 꼭 새로 table을 생성해주세요.

# 🌈 Success criteria
1. 사용자는 첫화면에서 로그인/회원가입할 수 있다.
2. 로그인에 성공하면 사용자는 요구사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- [x] 도메인별로 mvc패턴을 고려해 클래스를 모두 작성하세요.
- [x] 제공된 테이블을 보고 entity클래스는 모두 작성하세요.
- [x] Dto 추가할 때 enum class 추가

# 👓 Review
1.  db scripts 업데이트 완료
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/ac0a248d-9362-4e00-98b5-202fe5f4d1b1)
2. 로그인 완료
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/334f4918-94de-4bd2-a797-f5a338b525cd)
3. 도서관리 메뉴 완료 ( 0 누르면 돌아가기)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/f045e3eb-3c65-467f-a7a7-ece9cf944ff5)
5. 재고관리 메뉴 완료 ( 0 누르면 돌아가기)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/7f733007-fe19-44a6-a421-d2b6daf92c3c)
6. 주문관리 메뉴 완료 (0 누르면 돌아가기)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/844d4357-3ba8-4937-86b3-dc90df500811)

**Comment by nnieun** [comment]
기본생성자 DTO 만들 때 생성하는데 기본생성자를 왜 쓰는지 이유가 궁금합니다.
-> 조회 결과 DTO 객체에 매핑할떄 마이바티스가 기본적으로 기본 생성자 호출하고 기본 생성자 없으면 오류 난다 
( 강의 5월 10일 9시 수업 영상에 44분 참고)

해결했습니담.

**Comment by nnieun** [comment]
OrderDto에서 쓰는 Status.java (enum)을 어디에 넣어야될지 모르겠어요 일단 model 폴더안에 넣어놨습니다.
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/1ea38676-2902-4ab0-a2e9-8dd9015464dd)
