### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by youngwoo2** [ssg-java3-240304/wms-book#24]
# 👉 공지
issue생성시, Assignees/Projects(wms-book)를 꼭 작성해주세요
pr생성시 각자의 issue를 꼭 링크해주세요.
db script가 업데이트 되었습니다. 꼭 새로 table을 생성해주세요.
# 🌈 Success criteria
1. 사용자는 첫화면에서 로그인/회원가입할 수 있습니다.
2. 로그인에 성공하면 사용자는 요구사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- [ ]  도메인별로 mvc패턴을 고려해 클래스를 모두 작성하세요.
- [ ] 제공된 테이블을 보고 entity클래스는 모두 작성하세요.
- [ ] <추가 할일 목록을 작성하고 실천합니다>

# 👓 Review
1. <스크린샷 등을 적극활용해 구현 결과를 공유합니다.>
- 로그인/ 메인메뉴 -> 도서관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/152594318/b5d5724f-8733-4df4-a6db-ac69550fecfa)
- 메인메뉴 -> 재고관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/152594318/21c8a754-e2fa-4ac9-b34d-0fbb8d5d8fe1)
- 메인메뉴 -> 주문관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/152594318/d20fdb2f-d1f0-4779-baad-76b949ee3624)

**Comment by youngwoo2** [comment]
Q. 세부 메뉴에서 0번 입력하여 메인메뉴로 돌아간 뒤 0번 입력하여 종료하려고 하면 한번에 종료가 안됩니다..
