### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/wms-book#26]
# 👉 공지
1. issue생성시, Assignees/Projects(wms-book)를 꼭 작성해주세요
2. pr생성시 각자의 issue를 꼭 링크해주세요.
3. db script가 업데이트 되었습니다. 꼭 새로 table을 생성해주세요.

# 🌈 Success criteria
1. 사용자는 첫화면에서 로그인/회원가입할 수 있습니다.
2. 로그인에 성공하면 사용자는 요구사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- 도메인별로 mvc패턴을 고려해 클래스를 모두 작성하세요.
   - [x] user
   - [x] book
   - [x] inventory
   - [x] order
- 제공된 테이블을 보고 entity클래스는 모두 작성하세요.
   - [x] user _ userId, userName, password, role, createAt
   - [x] book _ bookId, title, author, description, price, category, createdAt
   - [x] inventory _ inventoryId, quantity, location, lastUpdated
   - [x] order _ orderId, ordererName, ordererAddress, orderDate, status
- 각각 도메인별로 view클래스 작성
   - [x] UserView
   - [x] BookView
   - [x] InventoryView
   - [x] OrderView
# 👓 Review
1. 도메인별로 mvc패턴을 고려한 클래스 작성
**book**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/33bccb2c-3ad8-421d-9741-8df0a9d6e998)
**inventory**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/0cf0d83b-f241-4a3b-bca3-f9794aa046f6)
**order**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/bd5c6e23-a264-460d-acc2-7088e4161c45)
**user**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/46f8a8ad-2163-479e-943e-39816cd847c6)

2. entity클래스는 작성
**book**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/aff19974-efa2-4882-b36b-2f765f4ff3f2)
**inventory**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/dc965042-e737-40c8-a067-1ba9ca9c4681)
**order**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/e23194d2-2477-4b10-9fc2-e0b20d441a68)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/0d6dedd0-da0f-4936-b864-7c1a23ef00b1)
**user**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/9f901789-38b3-4ccd-b12d-cd16698aaf0e)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/dee0df28-17f5-43be-aecd-f0d173863535)

3. 각각 도메인 view 작성
**book**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/06beae41-3f63-420c-adb0-dc727358b9a9)
**inventory**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/3ca0b653-debe-4f62-a181-56def3013bae)
**order**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/4cb18aa2-73c7-4164-9292-f795381f7336)
**user**
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/1548bdfc-8c6b-493b-8e6a-af3e9a737650)
