### ISSUE TITLE
[1일] 프로젝트 개발 환경을 설정합니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/wms-book#3]
# 🌈 Success criteria
1. db를 구축합니다. book계정으로 wms_book_db에 테이블/샘플데이터를 추가합니다.
2. gradle 프로젝트를 생성하고, mybatis 실행환경을 설정합니다.
3. 적절히 SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👷To-do
- [x] 로컬 mysql에 계정 book/book과 스키마 wms_book_db를 생성합니다.
- [x] root계정으로 book계정을 만듭니다. (패스워드 book)
- [x] root계정에서 wms_book_db를 생성합니다.
- [x] book계정이 wms_book_db의 사용권한을 부여합니다.
- [x] root계정에서 wms_book_db에 wms_book_db.sql을 실행합니다.
- [x] book계정에서도 wms_book_db 스키마를 생성하고 .sql을 실행합니다.
- [x] MVC패턴을 적용해 폴더와 클래스를 생성합니다.
- [x] MyBatis 환경설정을 합니다.
- [x] mybatis-config.xml, build.gradle, MyBatisTemplate을 작성합니다.
- [x] SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👓 Review
1. <테스트 결과 스크린샷등 각종 이미지를 적극적으로 첨부합니다.> 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/b29513ce-196d-4a14-8cfb-08310d1ce9b1)

**Comment by shqkel** [comment]
우어~ 빠른데요 👍
