### ISSUE TITLE
[2일] 요구사항을 반영해 사용자 메뉴화면을 계층적으로 구성합니다.

### ISSUE THREAD

**Issue by tjpark312** [ssg-java3-240304/wms-book#32]
# 👉 공지
1. issue생성시, Assignees/Projects(wms-book)를 꼭 작성해주세요
2. pr생성시 각자의 issue를 꼭 링크해주세요.
3. db script가 업데이트 되었습니다. 꼭 새로 table을 생성해주세요.

# 🌈 Success criteria
1. 사용자는 첫화면에서 로그인/회원가입할 수 있습니다.
2. 로그인에 성공하면 사용자는 요구사항을 반영한 메뉴를 계층적으로 확인할 수 있어야 합니다.

# 👷To-do
- [x] 도메인별로 mvc패턴을 고려해 클래스를 모두 작성하세요.
- [x] 제공된 테이블을 보고 entity클래스는 모두 작성하세요.
- [x] <추가 할일 목록을 작성하고 실천합니다> 

# 👓 Review
-- 로그인 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237157/f3cad3d7-8a67-4682-8df9-1da19a624ec2)

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237157/89baf08f-c2a0-4101-a64a-ad062d68b178)

--재고 관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237157/8521e74f-2803-49a6-9b30-d16347b95683)

--도서 관리
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237157/8dd20ef0-3f2f-47a0-9a21-31f38959f95e)

--주문 관리 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237157/7c4f1370-3141-487d-9e69-6f3b77c7eb8e)

**Comment by tjpark312** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237157/f20db19a-42ef-4b03-95ae-5665800c435a)

뒤로 가는것  mainMenu 메소드를 호출해서 사용하고 있는데 이렇게 하는게 맞는건지 잘 모르겠습니다.

**Comment by Hong-ji-min** [comment]
return하면 원래 메소드 호출했던 곳으로 다시 돌아가는 걸로 압니닷!
