### ISSUE TITLE
[3일] 사용자는 인증후 도서관리 기능을 이용할 수 있습니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/wms-book#37]
# 🌈 Success criteria
1. 사용자는 첫 로그인화면에서 id/password를 입력하고 로그인할 수 있습니다.
2. 로그인에 성공하면 AuthManager클래스에서 static필드인 loginUser에서 로그인한 회원객체를 관리합니다.
3. 로그아웃하면 AuthManager클래스의 static필드인 loginUser를 null로 처리합니다.
4. AuthManager는 인증관련 추가기능을 static메소드로 제공합니다. 
  - `isLogin():boolean` <static>
  - `login(User):void` <static>
  - `getLoginUser():User` <static>
  - `logout():void` <static>
6. 로그인에 필요한 테스트코드도 작성합니다.

# 👷To-do
- [x]  로그인에 필요한 쿼리를 고민하고, Dao Mapper테스트를 작성합니다.
- [x] mvc패턴 흐름에 맞춰 인증기능을 구현합니다.
- [x]  userController(), userService(), userMapper(), user-mapper.xml 작성
- [x]  AuthManager 클래스 구현하기

# 👓 Review
1. <스크린샷 등을 적극활용해 구현 결과를 공유합니다.>
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/2383e4ce-d92e-4f50-a438-be5e100cdcbf)
->UserMapperTest 결과 찍어보기

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/a746d578-6528-4389-93b5-182e8c0bf86a)
- 시작[로그인화면]

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/2210ad80-0f5e-45cb-96e9-28810d03ea71)
- 아이디/비밀번호/직책 확인 후 잘못 입력 시 다시 입력요청

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/25059c06-cb9f-40af-a987-79eabb7127f3)
- 올바른 정보 입력 시 로그인 성공

**Comment by seongyeongit** [comment]
열심히 두뇌를 사용해서 이슈에 맞게 코드가 정상적으로 돌아가게 만들었지만 뭔가 찜찜한 느낌이 듭니다...
필요 없는 코드들이 있을 것 같다는 생각이 드는데 어디가 그런 것일까는 잘 모르겠습니다...😅

**Comment by seongyeongit** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/b9f2a5d8-b8b6-42be-9a27-4d0875e925a5)
Q)깃허브 이슈에 사진 업로드 및 코멘트 등록 후 pr 보내려고 확인하는데 건드리지도 않은 다른 분들의 파일 하위에 bin 폴더가 생깁니다.. 이유가 뭘까요!?😥
-> 1일차 이슈에 대한 pr 보내기 전에도 제 폴더 하위에 bin 폴더가 생성되어 삭제 후 보냈는데
이번엔 다른 분들 하위에 bin 폴더들이 생겨서 이번에도 일일이 지워야 하는 불편함이 있습니다!!

**Comment by seongyeongit** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/6e953b87-e896-419d-8aaa-f2d58a869dda)
Q2) 관례적으로 대문자 사용하는 걸로 기억하는데 데이터베이스 상에 소문자라서 소문자로 작성하였습니다.
타입핸들러를 사용해서 데이터베이스와 Java 코드 간의 열거형 상수와 값의 변환을 자동으로 처리해야 할까요?
제 생각에는 Java에서는 문제 없이 컴파일되니 우선은 이에 대해 알고 있는 상태로 다음 단계 수행하는 게 우선순위 상 맞는 것 같은데 그래도 코드 구현 과정에서 궁금증이 생겨 질문 남겨놓습니다!
