### ISSUE TITLE
[3일] 사용자는 인증후 도서관리 기능을 이용할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/wms-book#38]
# 🌈 Success criteria
1. 사용자는 첫 로그인화면에서 id/password를 입력하고 로그인할 수 있습니다.
2. 로그인에 성공하면 AuthManager클래스에서 static필드인 loginUser에서 로그인한 회원객체를 관리합니다.
3. 로그아웃하면 AuthManager클래스의 static필드인 loginUser를 null로 처리합니다.
4. AuthManager는 인증관련 추가기능을 static메소드로 제공합니다. 
  - `isLogin():boolean` <static>
  - `login(User):void` <static>
  - `getLoginUser():User` <static>
  - `logout():void` <static>
6. 로그인에 필요한 테스트 코드도 작성합니다.

# 👷To-do
- [x] [2일차] Account Dto 수정 - 모든 테이블 모두 넣기
- [x] [2일차] enum 위치 변경 ( dto폴더 안에 넣어놓기) , enum 영문 안 쓰고 한글만 쓸꺼면 ("한글") 굳이 안 해도 됨 수정하기->영어로 수정함
- [x]  로그인에 필요한 쿼리를 고민하고, Dao Mapper테스트를 작성합니다.
- [x] mvc패턴 흐름에 맞춰 인증기능을 구현합니다.

# 👓 Review
1. role이 manager가 아닐경우 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/9e8a0495-2ba2-4818-97d4-f02591548ca0)
[테스트코드]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/90379c25-6ac3-4d75-813a-6118f7adb1bb)

2. 존재하지 않는 계정일 경우
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/1f2efbdb-5105-41a0-8c6f-1734f4b70bc3)
[테스트코드]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/994a6b73-1ade-41dc-a9ff-a6a5dc818aa8)

3. 로그인 성공
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/2d30e3bc-917c-4a12-ada5-cd1d447c4f3f)
[테스트코드]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/fe499c22-1806-4cdf-840b-32cfa3aa7342)

**Comment by nnieun** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/acd15095-2b6b-48e6-bd3a-8d9d2487e6a0)
ENUM을 대문자로 하면 오류가납니다.. 오류 메세지가 DB와 다르다고 하여 DB와 같이 소문자로 바꿔서 오류는 해결했습니다.
근데 ENUM은 대문자로 쓰는게 규칙이라고 하는데 소문자로 바꿔도 되는 건지 궁금합니다.

**Comment by nnieun** [comment]
AuthManager클래스를 만들어서 로그인된 계정 객체를 관리한다고 하는데 어디에 쓰는건지 궁금합니다, 현재는 만들기만 하면 되는건가요??
