### ISSUE TITLE
[3일] 사용자는 인증후 도서관리 기능을 이용할 수 있습니다.

### ISSUE THREAD

**Issue by youngwoo2** [ssg-java3-240304/wms-book#39]
# 🌈 Success criteria
1. 사용자는 첫 로그인화면에서 id/password를 입력하고 로그인할 수 있습니다.
2. 로그인에 성공하면 AuthManager클래스에서 static필드인 loginUser에서 로그인한 회원객체를 관리합니다.
3. 로그아웃하면 AuthManager클래스의 static필드인 loginUser를 null로 처리합니다.
4. AuthManager는 인증관련 추가기능을 static메소드로 제공합니다. 
  - `isLogin():boolean` <static>
  - `login(User):void` <static>
  - `getLoginUser():User` <static>
  - `logout():void` <static>
6. 로그인에 필요한 테스트코드도 작성합니다.

# 👷To-do
- [ ]  로그인에 필요한 쿼리를 고민하고, Dao Mapper테스트를 작성합니다.
- [ ] mvc패턴 흐름에 맞춰 인증기능을 구현합니다.
- [ ] <추가 할일 목록을 작성하고 실천합니다>

# 👓 Review
1. <스크린샷 등을 적극활용해 구현 결과를 공유합니다.>
- 로그인 검증(id/비밀번호가 다른경우 | 사용자 역할이 'manager'가 아닌경우)
![image](https://github.com/ssg-java3-240304/wms-book/assets/152594318/ff17db56-7044-4832-b722-0fac69427960)
- 로그인 성공
![image](https://github.com/ssg-java3-240304/wms-book/assets/152594318/31dba2dd-b8a2-4771-96ea-e3a513d0b4ac)

- 테스트 코드
![image](https://github.com/ssg-java3-240304/wms-book/assets/152594318/49534279-3072-4e40-acd2-724d089a9ce0)

**Comment by youngwoo2** [comment]
Q1.  AuthManager클래스의 역할을 제대로 이해하지 못하여 만들지 않았습니다.

Q2. 데이터베이스에 저장된 role 값이 "admin"인데 enum 상수 이름이 ADMIN이여서 오류가 납니다..(EnumTypeHandler 사용..?)
