### ISSUE TITLE
[3일] 사용자는 인증후 도서관리 기능을 이용할 수 있습니다.

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/wms-book#40]
# 🌈 Success criteria
1. 사용자는 첫 로그인화면에서 id/password를 입력하고 로그인할 수 있습니다.
2. 로그인에 성공하면 AuthManager클래스에서 static필드인 loginUser에서 로그인한 회원객체를 관리합니다.
3. 로그아웃하면 AuthManager클래스의 static필드인 loginUser를 null로 처리합니다.
4. AuthManager는 인증관련 추가기능을 static메소드로 제공합니다. 
  - `isLogin():boolean` <static>
  - `login(User):void` <static>
  - `getLoginUser():User` <static>
  - `logout():void` <static>
6. 로그인에 필요한 테스트코드도 작성합니다.

# 👷To-do
- [ ] 사용자가 로그인을 할 수 있도록 합니다.
- [ ] 로그인에 실패했을 경우, 다시 아이디/비밀번호를 입력할 수 있도록 합니다. 
- [ ] 로그인에 성공했을 경우, 메인메뉴를 볼 수 있도록 합니다.

# 👓 Review
1. <스크린샷 등을 적극활용해 구현 결과를 공유합니다.>

**Comment by jeonhyeonseon** [comment]
`isLogin():boolean` 부분을 사용하고 싶은데 어떻게 사용해야할지 잘 모르겠어요..
