### ISSUE TITLE
[3일] 사용자는 인증후 도서관리 기능을 이용할 수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/wms-book#47]
# 🌈 Success criteria
1. 사용자는 첫 로그인화면에서 id/password를 입력하고 로그인할 수 있습니다.
2. 로그인에 성공하면 AuthManager클래스에서 static필드인 loginUser에서 로그인한 회원객체를 관리합니다.
3. 로그아웃하면 AuthManager클래스의 static필드인 loginUser를 null로 처리합니다.
4. AuthManager는 인증관련 추가기능을 static메소드로 제공합니다. 
  - `isLogin():boolean` <static>
  - `login(User):void` <static>
  - `getLoginUser():User` <static>
  - `logout():void` <static>
6. 로그인에 필요한 테스트 코드도 작성합니다.

# 👷To-do
- [x]  로그인에 필요한 쿼리를 고민하고, Dao Mapper테스트를 작성합니다.
- [x] mvc패턴 흐름에 맞춰 인증 기능을 구현합니다.
- [x] loginView(), userController(), userService(), userMapper(), user-mapper.xml 작성
- [x]  AuthManager 클래스 구현하기

# 👓 Review
로그인 할때 id,password, Role을 확인합니다
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/a89b3756-f3fc-4112-9bb5-dd5bb7de9a88)\

로그인 성공 테스트
id, password가 db에 있고 Role이 manager인 경우
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/7d1210ab-b17b-43bc-8aec-365e92d41be3)

**Comment by vlshzl35** [comment]
AuthManager를 구현하긴 했는데 어떻게 사용할지 감이 안잡힌다

**Comment by vlshzl35** [comment]
mainMenu에서 로그아웃을 누르면 왜 loginMenu의 case "2"가 실행이 되는것인가요?
디버그를 해도 바로 넘어가기만 해서 잘 모르겠습니다. break를 꼭 넣어줘야 while문으로 이동합니다

<case 2 실행>
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/eb25d18f-24e1-453c-8d70-ffeed24f87de)

<loginMenu 코드>
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/a846c0ec-b0be-4a24-b886-05e01b757130)

<mainMenu 코드>
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/07e846ac-0d1f-4f38-8ca4-df303ed8b651)
