### ISSUE TITLE
[4일] 도서관리자는 도서 목록 조회 및 검색 할수 있습니다. 

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/wms-book#50]
# 100% 완료하지 않아도 할수 있는 한 구현해서 pr을 날려야 합니다. 점진적으로 완성해 갈 수 있습니다!

# 🌈 Success criteria
1.  인증한 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
4. 인증한 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다.
5. 또 도서명, 저자, 카테고리, 가격 등을 기준으로 검색할수 있습니다.
6. dao테스트 코드를 통해 쿼리와 결과집합 처리를 우선 확인해야 합니다.
7. mvc패턴 흐름을 고려해서 도서 조회/검색 기능을 구현합니다.

# 👷To-do
- [x]  [3일차수정] AuthManager를 이용한 인증처리 작성하기 (로그인에 성공하면 AuthManager를 통해 로그인처리해야 합니다)
- [x] 인증한 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
- [x] 인증한 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다. 
- [x]  도서명, 저자, 카테고리, 가격 등을 기준으로 검색할수 있습니다.

# 👓 Review
1. 전체 목록 조회 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/628eab84-bbcb-4f36-9067-20e84f4722e4)

2. 도서아이디 입력 후 도서 1건을 조회할 수있습니다.
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/7ad3c7d2-6d93-40c4-8e57-5e7a41c222b7)

3. 도서명,저자,카테고리,가격 등을 기준으로 검색

3.1 도서명 ![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/4db434cb-652a-4d07-bab7-bc1fb7cf1b1d)

3.2 저자 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/9eb4a8ad-2ef1-4475-9e43-d2250b802ade)

3.3 카테고리
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/c1312c92-a41d-4b57-9e42-695598e21406)

3.4 가격 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/156f6af7-f903-47d5-9902-9c87abe8d7e9)

**Comment by nnieun** [comment]
~ 주말에 추가하기 ~ (8,9일 안에)
- [ ] 도서명 검색 할 때 부분 검색 추가 하기 (쿼리에 like 추가 !)
- [ ] 가격 검색할 때 start end 추가해서 여러개로 검색하기
