### ISSUE TITLE
[4일] 도서관리자는 도서 목록 조회 및 검색 할수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/wms-book#51]
# 👉 공지
1. 일일 이슈가 밀리지 않도록 주의하세요. 지금 이 작업은 결코 쉽지않습니다. 집중만이 살길입니다. 주말이어도 할때는 합시다!
2. 오늘의 이슈는 DQL쿼리에 대한 것입니다. 하나를 잘 해결하면, 여러 건의 패턴이 비슷하다는 것을 알수 있습니다. 성공을 기원합니다.
3. 100% 완료하지 않아도 할수 있는 한 구현해서 pr을 날려야 합니다. 점진적으로 완성해 갈 수 있습니다!

# 🌈 Success criteria
1.  인증한 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
2. 인증한 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다..
3. 또 도서명, 저자, 카테고리, 가격 등을 기준으로 검색할수 있습니다.
4. dao테스트 코드를 통해 쿼리와 결과집합 처리를 우선 확인해야 합니다.
5. mvc패턴 흐름을 고려해서 도서 조회/검색 기능을 구현합니다.

# 👷To-do
- [x]  3일차 수정. 로그인을 성공하면 AuthManager에서 로그인정보를 관리합니다
- [x] 인증한 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
- [x] 인증한 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다.
- [x] 또 도서명, 저자, 카테고리, 가격 등을 기준으로 검색할수 있습니다.
# 👓 Review
1. 도서 전체 목록 조회
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/70757991-5736-4ac4-85f5-56979c1c973f)

2.  도서 ID로 검색
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/32003716-6ee9-4c5c-ae7b-032e55e681d1)

**Comment by vlshzl35** [comment]
bookID 조회만 가능하고 도서명, 저자, 카테고리, 가격 기준으로는 조회가 되지 않습니다. 디버깅해보니 view까지 값은 잘 전달하는 것 같은데..
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/c5311b79-8971-4512-b708-401d07de22df)

Test에서 assertFalse(book.isEmpty())가 true가 나오는걸 보면 sql문이 이상한 것 같긴한데 정확히 모르겠습니다
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/191c7b65-45a1-440f-9691-f49c90d2f653)
