### ISSUE TITLE
[4일] 도서관리자는 도서 목록 조회 및 검색 할수 있습니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/wms-book#52]
# 👉 공지
1. 일일 이슈가 밀리지 않도록 주의하세요. 지금 이 작업은 결코 쉽지않습니다. 집중만이 살길입니다. 주말이어도 할때는 합시다!
2. 오늘의 이슈는 DQL쿼리에 대한 것입니다. 하나를 잘 해결하면, 여러 건의 패턴이 비슷하다는 것을 알수 있습니다. 성공을 기원합니다.
3. 100% 완료하지 않아도 할수 있는 한 구현해서 pr을 날려야 합니다. 점진적으로 완성해 갈 수 있습니다!

# 🌈 Success criteria
1. 인증한 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
2. 인증한 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다.
3. 또 도서명, 저자, 카테고리, 가격 등을 기준으로 검색할수 있습니다.
4. dao테스트 코드를 통해 쿼리와 결과집합 처리를 우선 확인해야 합니다.
5. mvc패턴 흐름을 고려해서 도서 조회/검색 기능을 구현합니다.

# 👷To-do
- [x] 인증에 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
- [x] 인증에 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다.
- [x] 도서명, 저자, 카테고리, 가격 등을 기준으로 검색할수 있습니다.
- [x] [3일차수정] AuthManger가 UserController를 사용하지 않고, UserController가 AuthManager를 사용하도록 수정
# 👓 Review
1. <스크린샷 등을 적극활용해 구현 결과를 공유합니다.>

[BookMapperTest]

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/cc85506d-07de-4f29-a996-d3e58b0e2122)
-> 전체조회

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/c30a67c2-12b7-4819-b2a8-2a1e93cabe41)
-> 도서 아이디로 조회

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/a92a7c01-965c-4ca7-81c5-d0f59f960bfe)
-> 기준으로 조회

[Main]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/00b2fe9c-42ee-4186-ad2a-ed869553fe36)
-> 전체 조회

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/4c1aca3f-92ec-4ccf-8e14-5d54d5cbb706)
-> 도서 아이디로 조회

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/77bca311-a62c-4cff-aa71-280c6473eb2b)
-> (기준: 1. 도서명)

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/42552e0e-884a-4855-9d21-401632056721)
-> (기준: 2.저자)

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/8412fa50-264c-46f6-8507-e47eda5500cc)
-> (기준: 3.카테고리)

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/3209d214-95ff-4366-a0d6-71e1485a4bda)
-> (기준: 4.가격)

**Comment by seongyeongit** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/a030e429-a2f0-4202-a215-d15794d4e1a8)
Q1) 이런식으로 엔터를 입력받아서 "잘못된 입력입니다"를 출력하는 것 같은데 nextLine().trim()으로  한 줄을 읽고 앞뒤 공백 제거시켜도 제대로 안먹는 것 같은데 해결방법이 궁금합니다!
