### ISSUE TITLE
[4일] 도서관리자는 도서 목록 조회 및 검색할 수 있습니다. 

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/wms-book#55]
# 👉 공지
1. 일일 이슈가 밀리지 않도록 주의하세요. 지금 이 작업은 결코 쉽지않습니다. 집중만이 살길입니다. 주말이어도 할때는 합시다!
2. 오늘의 이슈는 DQL쿼리에 대한 것입니다. 하나를 잘 해결하면, 여러 건의 패턴이 비슷하다는 것을 알수 있습니다. 성공을 기원합니다.
3. 100% 완료하지 않아도 할수 있는 한 구현해서 pr을 날려야 합니다. 점진적으로 완성해 갈 수 있습니다!

# 🌈 Success criteria
1.  인증한 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
4. 인증한 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다.
5. 또 도서명, 저자, 카테고리, 가격 등을 기준으로 검색할수 있습니다.
6. dao테스트 코드를 통해 쿼리와 결과집합 처리를 우선 확인해야 합니다.
7. mvc패턴 흐름을 고려해서 도서 조회/검색 기능을 구현합니다.

# 👷To-do
- [ ]  인증을 성공한 도서관리자는 도서관리메뉴를 통해 전체 목록을 조회할 수 있습니다.
- [ ] 인증을 성공한 도서관리자는 도서 아이디를 입력하고, 해당 도서 1건을 조회할 수 있습니다.
- [ ] 도서명, 저자, 카테고리, 가격 등을 기준으로 검색할 수 있습니다.

# 👓 Review
1. 도서 목록 전체 조회 test
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/ce3385d5-62d0-41e3-9f3e-6314a1a1d3ad)
2. 도서 아이디로 조회 test
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/b2383780-41ac-4b27-a5e1-904c35163765)
3. 도서명 검색 test
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/2abea450-78c0-40cf-ae11-45f1e51d8af5)
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/02371e42-c74a-499e-9806-a3e7c5b8a28a)
4. 저자 검색 test
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/85151055-117a-4e42-9226-5713f793769d)

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/91ef9b0f-10b2-4253-a83a-6d8eee096a1d)
도서 조건검색 부분을 어떻게 구현해야할지 잘 모르겠습니다..

**Comment by jeonhyeonseon** [comment]
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/981292ea-07fe-4137-b1e9-63b75e96aa39)
도서 아이디 조회 후 다음 화면창이 나오지 않을 때 어떻게 수정해야하는지 생각하고 수정하기
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/54dd715c-e6b5-41a5-93dc-7f23c0959069)

**Comment by jeonhyeonseon** [comment]
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/e39092a0-2d32-4fa6-a36d-d2f3217a2e6d)
해당 도서 목록을 찾지 못하는 경우 추가적으로 해야하는 것 찾기

![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/c08e802c-be12-481a-9b58-598f3de290fc)
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/b1d06808-8c26-4577-ad84-db2ce4bea31e)
`sc.next()`가 아니라 `sc.nextLine()`으로 작성해야 띄어쓰기도 적용이 된다.

**Comment by jeonhyeonseon** [comment]
![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/4b8fea2c-33dd-4bf4-b393-f5843a48958c)

왜 오류가 난 건지 잘 모르겠습니다
