### ISSUE TITLE
[5일] 도서관리자는 도서정보를 등록/수정/삭제 할 수 있습니다. 

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/wms-book#69]
# 👉 공지
1. 오늘 이슈까지 완료한다면, 앱에서 하나의 테이블에 대한 CRUD처리를 완성하는 것입니다. 
2. 도서관리가 아닌 다른 앱을 만들어도 이 기본 CRUD는 유사하게 적용가능할 거에요. 
3. 하나의 테이블에 대한것은 이제 할수 있을것 같다는 자신감이 생겨야 합니다. 그렇지 않다면 CRUD 중에 미흡한 부분이 있는 것을 한번 체크해보고, 보완합시다 👊 

# 🌈 Success criteria
1. 도서관리자는 인증후 도서관리 메뉴에서 도서를 등록/수정/삭제 할 수 있습니다.
2. 도서 수정은 도서아이디와 등록일을 제외한 모든 정보를 일괄수정합니다.
3. 도서 삭제는 도서아이디를 입력받아 삭제처리합니다.
4. 도서등록/수정/삭제 Dao처리는 테스트코드로 검증해야 합니다.

# 👷To-do
- [x] 도서관리자는 도서명, 저자, 설명, 가격, 카테고리를 입력하여 도서 등록을 할 수 있습니다.
- [x] 도서관리자는 도서명, 저자, 설명, 가격, 카테고리를 입력하여 수정할 수 있습니다.
- [x] 도서관리자는 도서아이디를 입력받아 해당 도서 정보를 삭제할 수 있습니다.

# 👓 Review
1. 도서 등록 test
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/f19599d5-d799-4117-ac3f-5e4b1defbae6)

2. 도서 수정

3. 도서 삭제
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/44745e6d-3ce2-4b97-93c1-fc03abaae9a8)

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/3e960a17-3dc0-4003-a295-504805ae9d3b)
`assertThat(result).isEqualTo(1);` 도서가 새로 등록되면서 삽입된 행의 수가 1이라는 의미를 가지고 있다.

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/4a21b8ab-9984-4fe9-bf2f-77fb6ff6fe3b) 
오류 발생
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/a8eb5c20-b932-488b-8604-a3afd9e35279)

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/545a0c50-a1aa-4f83-9609-93c16a6e61fa)
오류 수정
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/8c069405-0c89-4b6d-85bf-ba94637fce63)

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/d974b176-da4a-4ea6-b43b-71668a079586)
삭제 후에는 도서가 존재하면 안되기 때문에 `isNotNull()`이 아닌 `isNull()`이 되어야 한다.
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/e1916d71-b4d4-4111-adf6-9d71339ca3f1)

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/0b69ca46-b869-4500-9c0d-f3d48376721f)

어떤 이유로 수정 실패라고 뜨는지 잘 모르겠습니다
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/0e23123d-09c4-4637-a860-66b139b51273)

![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/fab077bb-edd6-4e9e-b9b4-e591848ad605)
해결 완료했습니다.
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/3f6ba27d-bba7-461d-8d66-98d5448f9fbd)

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/07c8dc03-3237-4597-b550-4c518ba3d57f)
도서명(제목)이 긴 도서를 등록 후 도서 조회를 누르면 아래 사진처럼 나옵니다..
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/a140288e-da6a-4a66-81e9-bb73e9d939b0)
