### ISSUE TITLE
[1일] 프로젝트 개발 환경을 설정합니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/wms-book#7]
# 🌈 Success criteria
1. db를 구축합니다. book계정으로 wms_book_db에 테이블/샘플데이터를 추가합니다.
2. gradle 프로젝트를 생성하고, mybatis 실행환경을 설정합니다.
3. 적절히 SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👷To-do
- [x]   로컬 mysql에 계정 book/book과 스키마 wms_book_db를 생성합니다.
- [x] wms_book_db에 테이블/샘플데이터를 추가합니다.
- [x] gradle 프로젝트를 생성합니다.
- [x] mybatis 실행환경을 설정합니다.
- [x]  SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👓 Review
1. db 구축
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/f25e3dbb-4788-49aa-8ee6-4d6a6ee76324)

2. test 결과
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/70a609e9-38f3-4d4c-b549-cb1ab24c1d44)
