### ISSUE TITLE
[5일] 도서관리자는 도서정보를 등록/수정/삭제 할 수 있습니다.

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/wms-book#76]
# 👉 공지
1. 오늘 이슈까지 완료한다면, 앱에서 하나의 테이블에 대한 CRUD처리를 완성하는 것입니다. 
2. 도서관리가 아닌 다른 앱을 만들어도 이 기본 CRUD는 유사하게 적용가능할 거에요. 
3. 하나의 테이블에 대한것은 이제 할수 있을것 같다는 자신감이 생겨야 합니다. 그렇지 않다면 CRUD 중에 미흡한 부분이 있는 것을 한번 체크해보고, 보완합시다 👊 

# 🌈 Success criteria
1. 도서관리자는 인증후 도서관리 메뉴에서 도서를 등록/수정/삭제 할 수 있습니다.
2. 도서 수정은 도서아이디와 등록일을 제외한 모든 정보를 일괄수정합니다.
3. 도서 삭제는 도서아이디를 입력받아 삭제처리합니다.
4. 도서등록/수정/삭제 Dao처리는 테스트코드로 검증해야 합니다.

# 👷To-do
- [x] 도서관리자는 인증후 도서관리 메뉴에서 도서를 등록/수정/삭제 할 수 있습니다.
- [x] 도서 수정은 도서아이디와 등록일을 제외한 모든 정보를 일괄수정합니다.
- [x] 도서 삭제는 도서아이디를 입력받아 삭제처리합니다.
- [x] 도서등록/수정/삭제 Dao처리는 테스트코드로 검증해야 합니다.

# 👓 Review
1. <테스트 결과 스크린샷등 각종 이미지를 적극적으로 첨부합니다.>
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/d01e3f7c-7641-4f1e-859b-020bfa81c30c)
-> 등록
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/1411ad74-c698-4632-a3ce-888004eaec81)
-> 등록결과확인
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/0428db36-afd8-4a26-885a-a127eee19f9e)
-> 수정
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/f07e5f47-e13e-47cd-b3a9-e5589c9e69c0)
-> 수정결과확인
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/e2102fec-1a98-492e-889f-5c6ae0998997)
-> 삭제
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/ef0bfde4-1b1d-49f1-82b6-38da9292d43f)
-> 삭제결과확인

테스트
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/95b7432f-fa2d-48da-a719-debd7b713478)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/4e6f31cb-7097-4c9b-bee5-55a4575d4173)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237255/fc1147a4-30c9-49c2-893f-e0b1b9f77706)

**Comment by seongyeongit** [comment]
시간이 없어서 테스트를 안만들고 먼저 코드를 짜봤는데 오히려 더 시간이 걸린 것 같은 느낌이다..
다시 제대로 순서에 맞게 코드를 짜는 연습을 해야겠다.
빨간 줄, 오류를 두려워하고 멘탈이 나가는 게 아닌 맞서 싸우는 감자가 되자!

**Comment by seongyeongit** [comment]
- searchcriteria 사용 이유
동적으로 if(mybatis에서 가능) 사용해서 일일이 비교하지 않고
객체로 따로 기준을 냅두는거
- bookmappertest
-> 3번째(기준으로) 테스트하는 코드 이상하게 함 & 테스트 코드에는 sout 그냥 보는 용도
- .isnotnull .isempty 등을 넣어라.
ex)
@DisplayName("동적SQL(if) - 메뉴이름 일부로 검색이 가능하다.")
@ParameterizedTest
@ValueSource(strings = {"라떼", "쥬스"})
void test1(String value) {
// given
SearchCriteria searchCriteria = new SearchCriteria();
searchCriteria.setName("name");
searchCriteria.setValue(value);
// when
List<MenuDto> menuList = menuMapper.searchMenu(searchCriteria);
System.out.println(menuList);
// then
assertThat(menuList)
.isNotNull()
.isNotEmpty()
.allMatch((menu) -> menu.getMenuName().contains(String.valueOf(searchCriteria.getValue())));
}
- key value 형식으로 map으로 만들어라
- junit.jupiter 어렵다. !
- userservice에서 authmanager 갖고 있다!? controller로 바꿔야 함( 안바꿔도 돌아가긴 함)

->위의 사항들을 고쳐야하는데 하루하루의 issue를 해결해나가는 것도 벅차다..
꼭 위의 추가 사항들을 고쳐보자❗

**Comment by seongyeongit** [comment]
**이번엔 내 폴더 하위에 bin 폴더가 생성되었다.
빨리 끝내고 자고 싶어서 캡쳐를 안하고 바로 해결하려고 했다. 
생길때마다 계속 내가 지우고 실행하면 돌아가긴 한다.**
