### ISSUE TITLE
[5일] 도서관리자는 도서정보를 등록/수정/삭제 할 수 있습니다. 

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/wms-book#78]
# 👉 공지
1. 오늘 이슈까지 완료한다면, 앱에서 하나의 테이블에 대한 CRUD처리를 완성하는 것입니다. 
2. 도서관리가 아닌 다른 앱을 만들어도 이 기본 CRUD는 유사하게 적용가능할 거에요. 
3. 하나의 테이블에 대한것은 이제 할수 있을것 같다는 자신감이 생겨야 합니다. 그렇지 않다면 CRUD 중에 미흡한 부분이 있는 것을 한번 체크해보고, 보완합시다 👊 

# 🌈 Success criteria
1. 도서관리자는 인증후 도서관리 메뉴에서 도서를 등록/수정/삭제 할 수 있습니다.
2. 도서 수정은 도서아이디와 등록일을 제외한 모든 정보를 일괄수정합니다.
3. 도서 삭제는 도서아이디를 입력받아 삭제처리합니다.
4. 도서등록/수정/삭제 Dao처리는 테스트코드로 검증해야 합니다.

# 👷To-do
- [x] 도서를 등록합니다.
- [x] 도서수정은 도서아이디와 등록일을 제외한 모든 정보를 일괄수정합니다.
- [x] 도서 삭제는 도서아이디를 입력받아 삭제처리합니다.
- [x] 도서등록/수정/삭제 Dao처리는 테스트코드로 검증해야 합니다.

# 👓 Review
1. 도서등록 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/305a8a1d-7d6a-42ce-9ba5-35b6f2553860)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/e20878b6-b4c0-4ab1-8858-6ea445c3b5f2)
2.도서삭제
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/997d3731-5b60-41cb-8fd3-40f64468215a)
3.도서수정
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/b7bab274-5c40-4de8-8e29-a6d81cf531b4)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/b356ee96-1362-4968-af44-3b6521cdb75d)

**Comment by nnieun** [comment]
도서 삭제를 하고 다시 삽입했을 때 삭제한 BookId를 건너뛰고 그 다음 순서 숫자가 삽입되는데 도중에 숫자가 비어있어도 괜찮은건가요? (ex) 31번 삭제하고 새로운도서 삽입 -> 32번)

**Comment by nnieun** [comment]
1~30번까지는 invertory에 fk가 걸려있어서 삭제가 안 되는데 새롭게 넣은 도서의 정보들은 삭제가 됩니다.
그래서 데이터를 입력해서 넣으면 왜 fk가 바로 안 걸리는지 궁금합니다. 
혹시 inventory 테이블에도 등록한 도서의 정보가 삽입되면 fk가 걸리나요? 

일단 1~30번까지 입력하면 fk관련 에러가 나서  (SQLIntegrityConstraintViolationException 관한 ) 예외처리를 해놨습니다.
