### ISSUE TITLE
[6일] 도서관리자는 고객주문을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by Hong-ji-min** [ssg-java3-240304/wms-book#82]
# 👉 공지
1. 드디어 트랜잭션입니다. 다수개의 dml쿼리를 서비스단에서 모아서 처리해보는 겁니다.
2. mybatis 수업코드 `03_mybatis_crud`의 주문등록과 아주 유사할겁니다. 적극적으로 참조하세요.
3. **코드 한줄한줄의 이해도 중요하지만, 전체흐름을 읽어내는 것이 중요합니다. 직접 mvc패턴과 처리내역등을 그려보세요. 마지막 리뷰에 그 그림도 첨부합시다 :)**

# 🌈 Success criteria
1. 임의의 고객주문서가 있다고 가정하고, 이를 토대로 도서관리자는 도서관리앱에 주문을 등록합니다.
2. 하나의 주문에는 여러종류의 책을 포함할 수 있으므로, tbl_order 테이블과 tbl_order_item테이블의 관계를 고려해야 합니다. 
3. 주문 등록시에는 한건의 tbl_order 등록 쿼리와 한건이상의 tbl_order_item 등록쿼리를 함께 트랜잭션처리해야 합니다.
4. 다음 샘플 도서주문서를 등록할 수 있도록 있도록 합니다.
```
도서 주문서
---------------
주문자 : 홍길동
배송지 : 서울시 강동구 풍납동 1234-56
주문일 : 2024-06-04T13:30

주문 목록
--------------
1. 딥러닝 실전 (도서번호 5번) 3권
2. 리눅스 커맨드라인 완벽정리(도서번호 8번) 2권
```

# 👷To-do
- [x]  한건의 주문을 등록하는 Dao 테스트를 작성합니다.
- [ ] 한건의 주문아이템을 등록하는 Dao테스트를 작성합니다.
- [x] view단 메뉴를 통해 한번에 주문정보/주문아이템 정보를 입력할수 있게 기능을 구현합니다.
- [x] 서비스단에서 트랜잭션 처리 코드를 작성합니다.

# 👓 Review
#### 1. 한 건의 주문 등록 TestCode
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/0f426531-2ac5-4637-af03-21c57bbb6212)

#### 2. 한번에 주문 정보/주문 아이템 정보 입력
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/8a6a452f-5d3a-4365-be80-878447012c7b)

#### 3. 트랜잭션 처리
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/13085025-bb0e-47da-8da5-f1be3c37d1a9)

**Comment by Hong-ji-min** [comment]
### 한건의 주문 아이템 등록 TestCode
![image](https://github.com/ssg-java3-240304/wms-book/assets/80135858/663f2119-46f5-49a6-abf1-317ab1383728)
- [ ] 한건의 주문아이템을 등록하는 테스트코드는 orderList가 null이라고 해서 수정해야함!!

**Comment by shqkel** [comment]
pr에는 테스트 코드가 없던 거 같던데ㅠ 
위의 스샷코드는 어디에 있나요?

> ### 한건의 주문 아이템 등록 TestCode
> ![image](https://private-user-images.githubusercontent.com/80135858/337968535-663f2119-46f5-49a6-abf1-317ab1383728.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5Mzg3OTQsIm5iZiI6MTcxNzkzODQ5NCwicGF0aCI6Ii84MDEzNTg1OC8zMzc5Njg1MzUtNjYzZjIxMTktNDZmNS00OWE2LWFiZjEtMzE3YWIxMzgzNzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEzMDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YmE4ZTZhMjExMTdiYjE3YzhhZmNmMzEwNjBiNjA2NWRhM2Q1Mzc1N2QwYjJkNWQxNDJmYmEwNmRlY2MzODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CL2l7Svy6IsktqktZDF5LzkZu1E4e5Dh42sU_kkPxgs)
> 
> * [ ]  한건의 주문아이템을 등록하는 테스트코드는 orderList가 null이라고 해서 수정해야함!!
