### ISSUE TITLE
[6일] 도서관리자는 고객주문을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/wms-book#83]
# 👉 공지
1. 드디어 트랜잭션입니다. 다수개의 dml쿼리를 서비스단에서 모아서 처리해보는 겁니다.
2. mybatis 수업코드 `03_mybatis_crud`의 주문등록과 아주 유사할겁니다. 적극적으로 참조하세요.
3. **코드 한줄한줄의 이해도 중요하지만, 전체흐름을 읽어내는 것이 중요합니다. 직접 mvc패턴과 처리내역등을 그려보세요. 마지막 리뷰에 그 그림도 첨부합시다 :)**

# 🌈 Success criteria
1. 임의의 고객주문서가 있다고 가정하고, 이를 토대로 도서관리자는 도서관리앱에 주문을 등록합니다.
2. 하나의 주문에는 여러종류의 책을 포함할 수 있으므로, tbl_order 테이블과 tbl_order_item테이블의 관계를 고려해야 합니다. 
3. 주문 등록시에는 한건의 tbl_order 등록 쿼리와 한건이상의 tbl_order_item 등록쿼리를 함께 트랜잭션처리해야 합니다.
4. 다음 샘플 도서주문서를 등록할 수 있도록 있도록 합니다.
```
도서 주문서 
---------------
주문자 : 홍길동
배송지 : 서울시 강동구 풍납동 1234-56
주문일 : 2024-06-04T13:30

-> order dto

주문 목록
--------------
1. 딥러닝 실전 (도서번호 5번) 3권
2. 리눅스 커맨드라인 완벽정리(도서번호 8번) 2권
```

-> order items

# 👷To-do
- [x]  한건의 주문을 등록하는 Dao 테스트를 작성합니다.
- [x] 한건의 주문아이템을 등록하는 Dao테스트를 작성합니다.
- [x] view단 메뉴를 통해 한번에 주문정보/주문아이템 정보를 입력할수 있게 기능을 구현합니다.
- [x] 서비스단에서 트랜잭션 처리 코드를 작성합니다.
- [x] 주문할 때 dto 넣는거 테이블 두개 조합해서 넣기

# 👓 Review
1. 주문생성 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/c155ea7a-f401-4980-82bb-425f8ae63f77)
2. 한건의 주문을 등록하는 Dao 테스트
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/8eab61c1-9411-429f-ac11-5e86fceb8a5f)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/52b0f632-a330-47df-b063-bf7255b241bf)

3. 한건의 주문아이템을 등록하는 Dao 테스트
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/934ea3ba-ccc8-4431-be07-5931be58ace8)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/adec8f74-803e-4b53-aec1-30fbe905c0bf)

**Comment by nnieun** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162238064/bff8566a-fe94-4d28-8412-6f80933eeaa9)
전에 주문생성 시도했을 때 오류가 났었지만 자동증가는 실행되어서 그부분이 비어있습니다. 찾아보니 자동 증가(auto increment) 필드는 트랜잭션이 완료되지 않더라도 새로운 ID를 할당합니다. (트랜잭션이 롤백되거나 중단되더라도, 자동 증가 값은 증가한 상태로 남게 됨) 이라고 해서 이유는 알았는데
이럴 땐 빈 숫자를 어떻게 해결하면 좋을지 궁금합니다.

**Comment by shqkel** [comment]
> ![image](https://private-user-images.githubusercontent.com/162238064/337942770-bff8566a-fe94-4d28-8412-6f80933eeaa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5Mzk0NjksIm5iZiI6MTcxNzkzOTE2OSwicGF0aCI6Ii8xNjIyMzgwNjQvMzM3OTQyNzcwLWJmZjg1NjZhLWZlOTQtNGQyOC04NDEyLTZmODA5MzNlZWFhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMzE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzcxMTg3NDFkMjE0YjMwMzYxYzkyMmQ0ZDY0ZDNkMmJkOWZkYzI2ZmFhMTFkZTFmMzkxOGVkNTQzZWFhMzNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RGHTu7ae5W3LVxXrDj_tuQPidUnsVVTbL3nsVHB0aWc) 전에 주문생성 시도했을 때 오류가 났었지만 자동증가는 실행되어서 그부분이 비어있습니다. 찾아보니 자동 증가(auto increment) 필드는 트랜잭션이 완료되지 않더라도 새로운 ID를 할당합니다. (트랜잭션이 롤백되거나 중단되더라도, 자동 증가 값은 증가한 상태로 남게 됨) 이라고 해서 이유는 알았는데 이럴 땐 빈 숫자를 어떻게 해결하면 좋을지 궁금합니다.

pk컬럼값은 보통 고유한 식별값이면 충분합니다. 숫자가 건너뛰어진것은 크게 문제 삼지 않습니다.
숫자를 건너뛰지 않고, 부여하려면, auto_increment대신 매번 마지막값 +1 한 값을 직접 부여하는 방법도 있습니다 😄
