### ISSUE TITLE
[6일] 도서관리자는 고객주문을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/wms-book#84]
# 👉 공지
1. 드디어 트랜잭션입니다. 다수개의 dml쿼리를 서비스단에서 모아서 처리해보는 겁니다.
2. mybatis 수업코드 `03_mybatis_crud`의 주문등록과 아주 유사할겁니다. 적극적으로 참조하세요.
3. **코드 한줄한줄의 이해도 중요하지만, 전체흐름을 읽어내는 것이 중요합니다. 직접 mvc패턴과 처리내역등을 그려보세요. 마지막 리뷰에 그 그림도 첨부합시다 :)**

# 🌈 Success criteria
1. 임의의 고객주문서가 있다고 가정하고, 이를 토대로 도서관리자는 도서관리앱에 주문을 등록합니다.
2. 하나의 주문에는 여러종류의 책을 포함할 수 있으므로, tbl_order 테이블과 tbl_order_item테이블의 관계를 고려해야 합니다. 
3. 주문 등록시에는 한건의 tbl_order 등록 쿼리와 한건이상의 tbl_order_item 등록쿼리를 함께 트랜잭션처리해야 합니다.
4. 다음 샘플 도서주문서를 등록할 수 있도록 있도록 합니다.
```
도서 주문서
---------------
주문자 : 홍길동
배송지 : 서울시 강동구 풍납동 1234-56
주문일 : 2024-06-04T13:30

주문 목록
--------------
1. 딥러닝 실전 (도서번호 5번) 3권
2. 리눅스 커맨드라인 완벽정리(도서번호 8번) 2권
```

# 👷To-do
- [x]  한건의 주문을 등록하는 Dao 테스트를 작성합니다.
- [x] 한건의 주문아이템을 등록하는 Dao테스트를 작성합니다.
- [x] view단 메뉴를 통해 한번에 주문정보/주문아이템 정보를 입력할수 있게 기능을 구현합니다.
- [x] orderService에서 트랜잭션 처리 코드를 작성합니다.

# 👓 Review
1. 주문 요청 view
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/cbfdcc4e-fbb7-458a-8324-c8253b846f20)

- tbl_order에 고객정보가 추가됐다
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/5dff5643-dfdd-4f94-a316-6a053641671e)

- 종류가 다른 책을 2권 주문해서 tbl_order_item에 같은 order_id를 가진 2개의 order_item_id열이 생성됐다.
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/e3b22944-f176-4227-9707-ccff0c33f948)

**Comment by vlshzl35** [comment]
하고싶지만 못하고 있는 예외처리
1. tbl_book에 없는 book_id를 입력하면 orderResultView에 "주문 실패"가 떴으면 좋겠는데 service단에서 catch문으로 빠지는건지 controller까지 오지않아서 -1을 반환해주지 않는다..

2. 추가 주문하시겠습니까?에서 입력이 y/n이 아닌 다른 것을 입력받아도 주문요청을 생성하는 dto가 while문 밖이라 무조건 실행된다.

B while문을 하나 더 두고싶다. break label을 사용해 볼까했는데 Bwhile문 안에서 break A를 하면 추가 주문 전 입력했던 내용을 모두 날라가서 어떻게 넣어야할지 모르겠다. 
![image](https://github.com/ssg-java3-240304/wms-book/assets/81032378/2d94a8c5-1063-444b-8923-ef83a7ed3077)

**Comment by shqkel** [comment]
https://github.com/ssg-java3-240304/wms-book/issues/84#issuecomment-2156072117

1. 없는 bookId로 주문등록 시도를 하는 것보다 미리 유효성검사를 해서 정확한 bookId로만 주문 등록 시도하는 것이 좋은 흐름입니다. 물론 말씀하신것처럼 주문실패에 대한 예외처리를 구현할 수도 있고요. 다만 예외처리는 view에서 하지않고 컨트롤러에서 하죠~
2. 또하나의 while문과 label을 통한 break/continue 가능해요. 좋은 시도입니당. 해보세요 👍
