### ISSUE TITLE
[6일] 도서관리자는 고객주문을 등록할 수 있습니다. 

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/wms-book#85]
# 👉 공지
1. 드디어 트랜잭션입니다. 다수개의 dml쿼리를 서비스단에서 모아서 처리해보는 겁니다.
2. mybatis 수업코드 `03_mybatis_crud`의 주문등록과 아주 유사할겁니다. 적극적으로 참조하세요.
3. **코드 한줄한줄의 이해도 중요하지만, 전체흐름을 읽어내는 것이 중요합니다. 직접 mvc패턴과 처리내역등을 그려보세요. 마지막 리뷰에 그 그림도 첨부합시다 :)**

# 🌈 Success criteria
1. 임의의 고객주문서가 있다고 가정하고, 이를 토대로 도서관리자는 도서관리앱에 주문을 등록합니다.
2. 하나의 주문에는 여러종류의 책을 포함할 수 있으므로, tbl_order 테이블과 tbl_order_item테이블의 관계를 고려해야 합니다. 
3. 주문 등록시에는 한건의 tbl_order 등록 쿼리와 한건이상의 tbl_order_item 등록쿼리를 함께 트랜잭션처리해야 합니다.
4. 다음 샘플 도서주문서를 등록할 수 있도록 있도록 합니다.
```
도서 주문서
---------------
주문자 : 홍길동
배송지 : 서울시 강동구 풍납동 1234-56
주문일 : 2024-06-04T13:30

주문 목록
--------------
1. 딥러닝 실전 (도서번호 5번) 3권
2. 리눅스 커맨드라인 완벽정리(도서번호 8번) 2권
```

# 👷To-do
- [ ]  한건의 주문을 등록하는 Dao 테스트를 작성합니다.
- [ ] 한건의 주문아이템을 등록하는 Dao테스트를 작성합니다.
- [ ] view단 메뉴를 통해 한번에 주문정보/주문아이템 정보를 입력할수 있게 기능을 구현합니다.
- [ ] 서비스단에서 트랜잭션 처리 코드를 작성합니다.

# 👓 Review
1.
![Uploading image.png…]()

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/19f37f90-5a8b-47c8-9298-056745c98cf2)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/e5541e0f-3321-4db2-a87f-dd3461f947ed)
오류가 나는 이유를 잘 모르겠습니다..
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/f5b45b94-f1b0-473b-b838-1b7ffe17a15a)
`mybatis-config.xml`에 작성했는지 확인하기..!

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/97843e80-fdc4-4373-9d2e-e00760e2d475)
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/a55d3329-87b8-4349-9ff0-0bc39e6536b8)
오타로 수정완료했습니다.

**Comment by jeonhyeonseon** [comment]
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/9b609550-8b76-468a-8d5a-874a73762c41)
실패하는 이유에 대해서 다시 생각하기

![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/cbf4ea5b-8ac4-4825-bc96-33bf7b91e86d)
받는 것이 order가 아닌 orderItem을 받아야 한다.

![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/f97f4807-ed1c-475a-9790-ace9a20b08ba)
예외를 던지는거 신경쓰기

![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/a92d2d1e-abf3-442f-ba44-03b1eaf348be)
`if(sc.next().toUpperCase().charAt(0) != 'Y')` toUpperCase()를 사용했기 때문에 y가 아닌 Y를 작성해야지 오류가 나지 않는다.

![Image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/83c6b703-e424-4177-bee7-d291b64db027)
해결 완료
