### ISSUE TITLE
[1일] 프로젝트 개발 환경을 설정합니다.

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/wms-book#9]
# 🌈 Success criteria
1. db를 구축합니다. book계정으로 wms_book_db에 테이블/샘플데이터를 추가합니다.
2. gradle 프로젝트를 생성하고, mybatis 실행환경을 설정합니다.
3. 적절히 SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👷To-do
- [ ] 로컬 mysql에 계정 root를 생성합니다.
- [ ] 로컬 mysql에 계정 book/book과 스키마 wms_book_db를 생성합니다.
- [ ] gradle 프로젝트를 생성하고, mybatis 실행환경을 설정합니다.
- [ ] 적절히 SqlSession을 가져오는 테스트 코드를 작성합니다.

# 👓 Review
1. db만들기
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/056bd196-b9c6-480c-a2b1-5c9055109d10)
2. 테스트 코드 
![image](https://github.com/ssg-java3-240304/wms-book/assets/162237209/d7fdd614-7a54-4404-ac8e-0b26052e107c)
